/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.Turntable3D;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int solid_blue=0x7f040001;
        public static final int solid_green=0x7f040002;
        public static final int solid_red=0x7f040000;
        public static final int solid_yellow=0x7f040003;
    }
    public static final class drawable {
        public static final int blue=0x7f020003;
        public static final int green=0x7f020004;
        public static final int icon=0x7f020000;
        public static final int red=0x7f020002;
        public static final int robot=0x7f020001;
        public static final int screen_background_black=0x7f020006;
        public static final int translucent_background=0x7f020007;
        public static final int transparent_background=0x7f020008;
        public static final int yellow=0x7f020005;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
    public static final class style {
        /**  Base application theme is the default theme. 
         */
        public static final int Theme=0x7f060000;
        /**  A theme that has a translucent background.  Here we explicitly specify
         that this theme is to inherit from the system's translucent theme,
         which sets up various attributes correctly.. 
         */
        public static final int Theme_Translucent=0x7f060001;
    }
}
