=head1 NAME

ubudroid-server - server applet for AndroBuntu/UbuDroid Android application

=head1 SYNOPSIS

ubudroid-server.py

=head1 DESCRIPTION

B<ubudroid-server> is an application to allow an Android handset to interact with the Ubuntu desktop.
The client application provides interfaces for media control, X10 home automation, and custom user scripts.

=head1 BUGS


=head1 AUTHORS

B<ubudroid-server> was written by Karl Ostmo <kostmo@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut
