/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.AndroBuntu;

public final class R {
    public static final class array {
        /**  Used in app/menu examples 
         */
        public static final int entries_list_preference=0x7f050001;
        /**  Used in app/menu examples 
         */
        public static final int entryvalues_list_preference=0x7f050002;
        public static final int flinger_destinations=0x7f050000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int solid_blue=0x7f060001;
        public static final int solid_green=0x7f060002;
        public static final int solid_red=0x7f060000;
        public static final int solid_yellow=0x7f060003;
    }
    public static final class drawable {
        public static final int blue=0x7f020005;
        public static final int green=0x7f020006;
        public static final int icon=0x7f020000;
        public static final int lightbulb_off=0x7f020001;
        public static final int minibuntu=0x7f020002;
        public static final int moon=0x7f020003;
        public static final int red=0x7f020004;
        public static final int screen_background_black=0x7f020008;
        public static final int translucent_background=0x7f020009;
        public static final int transparent_background=0x7f02000a;
        public static final int yellow=0x7f020007;
    }
    public static final class id {
        public static final int appliance_selector=0x7f090006;
        public static final int dimmer_bar=0x7f090009;
        public static final int flinger_destination_selector=0x7f090000;
        public static final int flingertext=0x7f090001;
        public static final int housecode_selector=0x7f090003;
        public static final int jotter_button=0x7f09000e;
        public static final int lightsoff_button=0x7f090004;
        public static final int lightson_button=0x7f090005;
        public static final int logo_button=0x7f09000f;
        public static final int media_button=0x7f09000b;
        public static final int screen_blank_button=0x7f09000a;
        public static final int scripts_button=0x7f09000d;
        public static final int slingle_light_off=0x7f090008;
        public static final int slingle_light_on=0x7f090007;
        public static final int textflinger_button=0x7f090002;
        public static final int x10_button=0x7f09000c;
    }
    public static final class layout {
        public static final int flinger=0x7f030000;
        public static final int lights=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f070002;
        public static final int default_hostname_string=0x7f07000a;
        public static final int default_port_number=0x7f07000e;
        public static final int dialog_based_preferences=0x7f070004;
        public static final int dialog_title_editint_preference=0x7f07000d;
        public static final int dialog_title_edittext_preference=0x7f070009;
        public static final int dialog_title_list_preference=0x7f070011;
        public static final int goodbye=0x7f070001;
        public static final int hello=0x7f070000;
        public static final int inline_preferences=0x7f070003;
        public static final int summary_editint_preference=0x7f07000c;
        public static final int summary_edittext_preference=0x7f070008;
        public static final int summary_list_preference=0x7f070010;
        public static final int summary_toggle_preference=0x7f070006;
        public static final int textflinger_button_title=0x7f070012;
        public static final int title_editint_preference=0x7f07000b;
        public static final int title_edittext_preference=0x7f070007;
        public static final int title_list_preference=0x7f07000f;
        public static final int title_toggle_preference=0x7f070005;
    }
    public static final class style {
        /**  Base application theme is the default theme. 
         */
        public static final int Theme=0x7f080000;
        /**  A theme that has a translucent background.  Here we explicitly specify
         that this theme is to inherit from the system's translucent theme,
         which sets up various attributes correctly.. 
         */
        public static final int Theme_Translucent=0x7f080001;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
